// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ResourcesList {
    /**
     * Creates a new ResourcesList instance.
     * @param {Partial<ResourcesList>} [$$source = {}] - The source object to create the ResourcesList.
     */
    constructor($$source = {}) {
        if (!("script" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["script"] = [];
        }
        if (!("css" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["css"] = [];
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["image"] = [];
        }
        if (!("dom" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dom"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourcesList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourcesList}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("script" in $$parsedSource) {
            $$parsedSource["script"] = $$createField0_0($$parsedSource["script"]);
        }
        if ("css" in $$parsedSource) {
            $$parsedSource["css"] = $$createField1_0($$parsedSource["css"]);
        }
        if ("image" in $$parsedSource) {
            $$parsedSource["image"] = $$createField2_0($$parsedSource["image"]);
        }
        if ("dom" in $$parsedSource) {
            $$parsedSource["dom"] = $$createField3_0($$parsedSource["dom"]);
        }
        return new ResourcesList(/** @type {Partial<ResourcesList>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
