// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * DownloadRecord 下载记录
 */
export class DownloadRecord {
    /**
     * Creates a new DownloadRecord instance.
     * @param {Partial<DownloadRecord>} [$$source = {}] - The source object to create the DownloadRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * 下载的 URL
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("site_name" in $$source)) {
            /**
             * 站点名称
             * @member
             * @type {string}
             */
            this["site_name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 状态：success, failed, processing
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("total_files" in $$source)) {
            /**
             * 总文件数
             * @member
             * @type {number}
             */
            this["total_files"] = 0;
        }
        if (!("downloaded" in $$source)) {
            /**
             * 已下载数
             * @member
             * @type {number}
             */
            this["downloaded"] = 0;
        }
        if (!("css_count" in $$source)) {
            /**
             * CSS 文件数
             * @member
             * @type {number}
             */
            this["css_count"] = 0;
        }
        if (!("script_count" in $$source)) {
            /**
             * JS 文件数
             * @member
             * @type {number}
             */
            this["script_count"] = 0;
        }
        if (!("image_count" in $$source)) {
            /**
             * 图片文件数
             * @member
             * @type {number}
             */
            this["image_count"] = 0;
        }
        if (!("video_count" in $$source)) {
            /**
             * 视频文件数
             * @member
             * @type {number}
             */
            this["video_count"] = 0;
        }
        if (!("error_msg" in $$source)) {
            /**
             * 错误信息
             * @member
             * @type {string}
             */
            this["error_msg"] = "";
        }
        if (!("start_time" in $$source)) {
            /**
             * 开始时间
             * @member
             * @type {time$0.Time}
             */
            this["start_time"] = null;
        }
        if (!("end_time" in $$source)) {
            /**
             * 结束时间
             * @member
             * @type {time$0.Time}
             */
            this["end_time"] = null;
        }
        if (!("duration" in $$source)) {
            /**
             * 耗时（秒）
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadRecord(/** @type {Partial<DownloadRecord>} */($$parsedSource));
    }
}
