// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NginxSiteConfig 站点配置结构
 */
export class NginxSiteConfig {
    /**
     * Creates a new NginxSiteConfig instance.
     * @param {Partial<NginxSiteConfig>} [$$source = {}] - The source object to create the NginxSiteConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 站点唯一ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 站点名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("domains" in $$source)) {
            /**
             * 域名列表
             * @member
             * @type {string[]}
             */
            this["domains"] = [];
        }
        if (!("port" in $$source)) {
            /**
             * 监听端口
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * 网站根目录路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("index" in $$source)) {
            /**
             * 默认首页文件
             * @member
             * @type {string}
             */
            this["index"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NginxSiteConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NginxSiteConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField2_0($$parsedSource["domains"]);
        }
        return new NginxSiteConfig(/** @type {Partial<NginxSiteConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
