// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * @param {string} obj
 * @returns {$CancellablePromise<boolean>}
 */
export function DownloadSite(obj) {
    return $Call.ByID(2539977978, obj);
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<services$0.ResourcesList | null>}
 */
export function GetResources(rawURL) {
    return $Call.ByID(2167352808, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = services$0.ResourcesList.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
