// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * EnvStatus 环境状态结构
 */
export class EnvStatus {
    /**
     * Creates a new EnvStatus instance.
     * @param {Partial<EnvStatus>} [$$source = {}] - The source object to create the EnvStatus.
     */
    constructor($$source = {}) {
        if (!("hasGo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasGo"] = false;
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("hasWails" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasWails"] = false;
        }
        if (!("wailsVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wailsVersion"] = "";
        }
        if (!("goPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goPath"] = "";
        }
        if (!("wailsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wailsPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvStatus(/** @type {Partial<EnvStatus>} */($$parsedSource));
    }
}

export class FileDir {
    /**
     * Creates a new FileDir instance.
     * @param {Partial<FileDir>} [$$source = {}] - The source object to create the FileDir.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modTime"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDir instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileDir}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileDir(/** @type {Partial<FileDir>} */($$parsedSource));
    }
}
